"""Shared API and job error code taxonomy."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Enumerated error codes shared by API envelopes and persisted jobs."""

    NOT_FOUND = "NOT_FOUND"
    INVALID_CURSOR = "INVALID_CURSOR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INPUT_INVALID = "INPUT_INVALID"
    INPUT_UNSUPPORTED_FORMAT = "INPUT_UNSUPPORTED_FORMAT"
    ADAPTER_UNAVAILABLE = "ADAPTER_UNAVAILABLE"
    ADAPTER_TIMEOUT = "ADAPTER_TIMEOUT"
    ADAPTER_FAILED = "ADAPTER_FAILED"
    STORAGE_FAILED = "STORAGE_FAILED"
    DB_CONFLICT = "DB_CONFLICT"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    JOB_CANCELLED = "JOB_CANCELLED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
